#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Render every blog post and the blog index from ONE template.

    python3 tools/gen_blog.py            # writes src/blog/<slug>/index.html × N and src/blog/index.html
    python3 tools/build_site.py          # then renders both trees as usual

Source of truth: tools/blog/posts/<slug>.json — one file per post with the
slug, category, ISO date (optional "updated"), keywords and, per language,
the title, the one-line lead and the body HTML. The writing lives there and
only there; this script never edits it.

What the template decides, once, for all 54 pages:
  · reading time, from the word count of THAT language's body (200 wpm),
    never a typed number
  · dates in each language's own format; an "Updated" line only when the
    JSON carries an updated date later than the published one, and
    dateModified in the structured data follows the same rule
  · related posts: three from the same category, ranked by shared
    keywords and then by date, balanced so that no post is left with
    nobody linking to it
  · previous / next by publication date
  · BlogPosting + BreadcrumbList structured data; the build localises
    headline, description and inLanguage per tree and rewrites hreflang
  · one quiet route into the app after the article, and the disclaimer

Both languages are emitted as data-lang-block pairs; tools/build_site.py
keeps one per tree, so the two trees are identical in structure by
construction."""
import glob, html, json, os, re, sys
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POSTS = os.path.join(ROOT, "tools", "blog", "posts")
SRC = os.path.join(ROOT, "src", "blog")
PLAY = "https://play.google.com/store/apps/details?id=com.fotokal.app"
WPM = 200

MONTHS_EN = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
MONTHS_ES = ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"]

def fmt_date(iso, lang):
    y, m, d = (int(x) for x in iso.split("-"))
    return "%s %d, %d" % (MONTHS_EN[m - 1], d, y) if lang == "en" else "%d de %s de %d" % (d, MONTHS_ES[m - 1], y)

def words(body_html):
    return len(re.sub(r"<[^>]+>", " ", body_html).split())

def minutes(body_html):
    return max(1, round(words(body_html) / WPM))

def esc(s):
    return html.escape(s, quote=True)

def strip_tags(s):
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", s)).strip()

def kwset(p):
    return set(k.strip().lower() for k in (p.get("keywords") or "").split(",") if k.strip())

# ── load ──────────────────────────────────────────────────────────────
posts = [json.load(open(f, encoding="utf-8")) for f in sorted(glob.glob(os.path.join(POSTS, "*.json")))]
by_slug = {p["slug"]: p for p in posts}
by_date = sorted(posts, key=lambda p: (p["date"], p["slug"]))
for p in posts:
    assert re.match(r"\d{4}-\d{2}-\d{2}$", p["date"]), p["slug"]
    if p.get("updated"):
        assert p["updated"] >= p["date"], ("updated before published", p["slug"])

# ── related: same category, keyword overlap, then nearest date; balanced ──
def related_for(p):
    mates = [q for q in posts if q["category"] == p["category"] and q["slug"] != p["slug"]]
    kw = kwset(p)
    mates.sort(key=lambda q: (-len(kw & kwset(q)), abs((date.fromisoformat(q["date"]) - date.fromisoformat(p["date"])).days), q["slug"]))
    return [q["slug"] for q in mates[:3]]

related = {p["slug"]: related_for(p) for p in posts}
# balance: every post should be linked from at least one other post's list
def inbound():
    c = {p["slug"]: 0 for p in posts}
    for s, r in related.items():
        for t in r:
            c[t] += 1
    return c
for _ in range(3):
    inb = inbound()
    for orphan in [s for s, n in inb.items() if n == 0]:
        cat = by_slug[orphan]["category"]
        mates = [q["slug"] for q in posts if q["category"] == cat and q["slug"] != orphan]
        if not mates:
            continue
        # put the orphan into the list of the mate whose current picks are the most-linked (cheapest to lose one)
        best, drop = None, None
        for m in mates:
            if orphan in related[m]:
                break
            picks = related[m]
            if not picks:
                continue
            victim = max(picks, key=lambda t: inb[t])
            if best is None or inb[victim] > inb[drop]:
                best, drop = m, victim
        else:
            if best is not None and inb[drop] > 1:
                related[best] = [orphan if t == drop else t for t in related[best]]
                inb = inbound()

# ── templates ─────────────────────────────────────────────────────────
HEAD = """<!DOCTYPE html>
<!-- GENERATED by tools/gen_blog.py from tools/blog/posts/{slug}.json — do not edit here. -->
<html lang="en" class="no-js">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title_en} — Fotocal</title>
  <meta name="description" content="{lead_en}">
  <meta name="keywords" content="{keywords}">
  <link rel="canonical" href="https://getfotocal.com/blog/{slug}/">
  <link rel="alternate" hreflang="en" href="https://getfotocal.com/blog/{slug}/">
  <link rel="alternate" hreflang="es" href="https://getfotocal.com/blog/{slug}/">
  <link rel="alternate" hreflang="x-default" href="https://getfotocal.com/blog/{slug}/">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="Fotocal">
  <meta property="og:title" content="{title_en}">
  <meta property="og:description" content="{lead_en}">
  <meta property="og:url" content="https://getfotocal.com/blog/{slug}/">
  <meta property="og:image" content="https://getfotocal.com/assets/og-image.png">
  <meta property="article:published_time" content="{date}">
  <meta property="article:modified_time" content="{modified}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{title_en}">
  <meta name="twitter:description" content="{lead_en}">
  <meta name="twitter:image" content="https://getfotocal.com/assets/og-image.png">
  <meta name="theme-color" media="(prefers-color-scheme: light)" content="#FFFFFF">
  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#121212">
  <script type="application/ld+json">{ld_post}</script>
  <script type="application/ld+json">{ld_crumbs}</script>
  <link rel="icon" type="image/png" sizes="32x32" href="../../assets/favicon-32.png?v=3">
  <link rel="icon" type="image/png" sizes="16x16" href="../../assets/favicon-16.png?v=3">
  <link rel="icon" href="../../assets/favicon.ico?v=3" sizes="32x32">
  <link rel="apple-touch-icon" sizes="180x180" href="../../assets/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="192x192" href="../../assets/icon-192.png">
  <link rel="manifest" href="../../site.webmanifest">
  <link rel="stylesheet" href="../../assets/css/fonts.css">
  <link rel="stylesheet" href="../../assets/css/site.css">
  <link rel="stylesheet" href="../../assets/css/home.css">
  <link rel="stylesheet" href="../../assets/css/features.css">
  <link rel="stylesheet" href="../../assets/css/blog.css">
</head>
<body class="page-fx page-post">
<div id="site-nav"></div>

<main id="main">
  <article class="post">
    <header class="post-head">
      <div class="container-narrow">
        <nav class="post-crumbs reveal" aria-label="Breadcrumb">
          <a href="../../" data-i18n="nav.home">Home</a><span class="sep" aria-hidden="true">/</span><a href="../" data-i18n="nav.blog">Blog</a><span class="sep" aria-hidden="true">/</span><a href="../?cat={cat}" data-i18n="blog.cat.{cat}">{cat_en}</a>
        </nav>
        <h1 class="post-title reveal" data-lang-block="en">{title_en}</h1>
        <h1 class="post-title reveal" data-lang-block="es">{title_es}</h1>
        <p class="post-lead reveal" data-lang-block="en">{lead_en}</p>
        <p class="post-lead reveal" data-lang-block="es">{lead_es}</p>
        <div class="post-meta reveal">
          <span data-lang-block="en"><time datetime="{date}">{date_en}</time>{updated_en}</span>
          <span data-lang-block="es"><time datetime="{date}">{date_es}</time>{updated_es}</span>
          <span class="dot" aria-hidden="true">&middot;</span>
          <span data-lang-block="en">{min_en} <span data-i18n="blog.min">min read</span></span>
          <span data-lang-block="es">{min_es} <span data-i18n="blog.min">min de lectura</span></span>
        </div>
      </div>
    </header>

    <figure class="post-cover reveal">
      <div class="container-narrow">
        <img src="../../assets/img/blog/{slug}.svg" width="1200" height="675" fetchpriority="high" decoding="async" alt="">
      </div>
    </figure>

    <div class="container-narrow">
      <div class="post-body reveal" data-lang-block="en">
{body_en}
      </div>
      <div class="post-body reveal" data-lang-block="es">
{body_es}
      </div>

      <p class="post-disclaimer reveal" data-i18n="blog.disclaimer">This article is general information, not medical advice.</p>

      <!--# One route into the app, after the article, stated as a fact
           the reader can act on. Free plan figures come from the app's
           gating code (src/lib/paywall.ts LIMITS): 2 photo scans a day. -->
      <aside class="ai-callout ai-callout-quiet post-app reveal">
        <div class="ai-callout-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 7h3l2-2h6l2 2h3v12H4z"/><circle cx="12" cy="13" r="3.5"/></svg></div>
        <div>
          <h4 data-i18n="blog.app.h">If you want to see this in your own meals</h4>
          <p data-i18n="blog.app.p">Fotocal logs a plate from a photo and shows the calories, macros and a health score. The free plan has no card and no time limit: 2 photo scans a day, the barcode scanner and Coach Kal without limits. Android only.</p>
          <p><a href="{play}" target="_blank" rel="noopener" data-i18n="cta.free">Get it free</a></p>
        </div>
      </aside>

      <nav class="post-nav reveal" aria-label="Previous and next article">
        {prev}
        {next}
      </nav>
    </div>
  </article>

  <section class="section sec-light-2 post-related">
    <div class="container">
      <header class="fx-chap">
        <span class="kicker reveal" data-i18n="blog.more">Keep reading</span>
        <h2 class="section-title reveal" data-i18n="blog.moreSub">More on this topic</h2>
      </header>
      <div class="habit-grid sf-grid-3">
{related}
      </div>
    </div>
  </section>
</main>

<div id="site-footer"></div>
<script src="../../assets/js/i18n.js"></script>
<script src="../../assets/js/layout.js" data-page="blog"></script>
<script src="../../assets/js/main.js"></script>
</body>
</html>
"""

CARD = """        <a class="habit-card sf-read post-card reveal" href="{href}"{delay}>
          <span class="log-tag" data-i18n="blog.cat.{cat}">{cat_en}</span>
          <h3 data-lang-block="en">{title_en}</h3>
          <h3 data-lang-block="es">{title_es}</h3>
          <p data-lang-block="en">{lead_en}</p>
          <p data-lang-block="es">{lead_es}</p>
          <span class="post-card-meta"><span data-lang-block="en">{date_en} · {min_en} <span data-i18n="blog.min">min read</span></span><span data-lang-block="es">{date_es} · {min_es} <span data-i18n="blog.min">min de lectura</span></span></span>
          <span class="fx-link" data-i18n="feat.read">Read →</span>
        </a>"""

NAVITEM = """<a class="post-nav-item{cls}" href="../{slug}/"><small data-i18n="blog.{which}">{label}</small><strong data-lang-block="en">{title_en}</strong><strong data-lang-block="es">{title_es}</strong></a>"""

CAT_EN = {"nutrition": "Nutrition", "weightloss": "Weight loss", "healthy": "Healthy eating", "diet": "Diet tips", "mindset": "Mindset",
          "fitness": "Fitness", "calories": "Calorie counting", "mealplan": "Meal planning", "lifestyle": "Lifestyle"}

def card(q, href, i=0):
    return CARD.format(href=href, delay=(' style="--rd:%.2fs"' % (0.06 * i)) if i else "", cat=q["category"], cat_en=CAT_EN[q["category"]],
                       title_en=q["en"]["title"], title_es=q["es"]["title"], lead_en=q["en"]["lead"], lead_es=q["es"]["lead"],
                       date_en=fmt_date(q["date"], "en"), date_es=fmt_date(q["date"], "es"), min_en=minutes(q["en"]["body"]), min_es=minutes(q["es"]["body"]))

def render_post(p, idx):
    prev_p = by_date[idx - 1] if idx > 0 else None
    next_p = by_date[idx + 1] if idx + 1 < len(by_date) else None
    modified = p.get("updated") or p["date"]
    upd_en = (' <span class="post-updated">Updated <time datetime="%s">%s</time></span>' % (p["updated"], fmt_date(p["updated"], "en"))) if p.get("updated") and p["updated"] != p["date"] else ""
    upd_es = (' <span class="post-updated">Actualizado <time datetime="%s">%s</time></span>' % (p["updated"], fmt_date(p["updated"], "es"))) if p.get("updated") and p["updated"] != p["date"] else ""
    ld_post = json.dumps({
        "@context": "https://schema.org", "@type": "BlogPosting",
        "headline": strip_tags(p["en"]["title"]), "description": strip_tags(p["en"]["lead"]),
        "datePublished": p["date"], "dateModified": modified,
        "author": {"@type": "Organization", "name": "Fotocal", "url": "https://getfotocal.com/about/"},
        "publisher": {"@type": "Organization", "name": "Fotocal", "logo": {"@type": "ImageObject", "url": "https://getfotocal.com/assets/img/logo.png"}},
        "mainEntityOfPage": {"@type": "WebPage", "@id": "https://getfotocal.com/blog/%s/" % p["slug"]},
        "image": "https://getfotocal.com/assets/img/blog/%s.svg" % p["slug"],
        "articleSection": CAT_EN[p["category"]], "keywords": p.get("keywords") or "",
        "wordCount": words(p["en"]["body"]), "isAccessibleForFree": True,
    }, ensure_ascii=False)
    ld_crumbs = json.dumps({"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "{{i18n:nav.home}}", "item": "https://getfotocal.com/"},
        {"@type": "ListItem", "position": 2, "name": "{{i18n:nav.blog}}", "item": "https://getfotocal.com/blog/"},
        {"@type": "ListItem", "position": 3, "name": strip_tags(p["en"]["title"]), "item": "https://getfotocal.com/blog/%s/" % p["slug"]}]}, ensure_ascii=False)
    prev_html = NAVITEM.format(cls="", slug=prev_p["slug"], which="prev", label="Previous article", title_en=prev_p["en"]["title"], title_es=prev_p["es"]["title"]) if prev_p else '<span class="post-nav-item post-nav-empty" aria-hidden="true"></span>'
    next_html = NAVITEM.format(cls=" post-nav-next", slug=next_p["slug"], which="next", label="Next article", title_en=next_p["en"]["title"], title_es=next_p["es"]["title"]) if next_p else '<span class="post-nav-item post-nav-empty" aria-hidden="true"></span>'
    rel = "\n".join(card(by_slug[s], "../%s/" % s, i) for i, s in enumerate(related[p["slug"]]))
    return HEAD.format(slug=p["slug"], title_en=esc(strip_tags(p["en"]["title"])), title_es=esc(strip_tags(p["es"]["title"])),
                       lead_en=esc(strip_tags(p["en"]["lead"])), lead_es=esc(strip_tags(p["es"]["lead"])), keywords=esc(p.get("keywords") or ""),
                       date=p["date"], modified=modified, date_en=fmt_date(p["date"], "en"), date_es=fmt_date(p["date"], "es"),
                       updated_en=upd_en, updated_es=upd_es, min_en=minutes(p["en"]["body"]), min_es=minutes(p["es"]["body"]),
                       cat=p["category"], cat_en=CAT_EN[p["category"]], body_en=p["en"]["body"], body_es=p["es"]["body"],
                       ld_post=ld_post, ld_crumbs=ld_crumbs, play=PLAY, prev=prev_html, next=next_html, related=rel)

# ── index ─────────────────────────────────────────────────────────────
INDEX = """<!DOCTYPE html>
<!-- GENERATED by tools/gen_blog.py from tools/blog/posts/*.json — do not edit here. -->
<html lang="en" class="no-js">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fotocal Blog — nutrition, calories and habits</title>
  <meta name="description" content="{count} practical, no-nonsense guides on nutrition, calorie counting, weight loss, macros and the everyday habits behind eating better.">
  <link rel="canonical" href="https://getfotocal.com/blog/">
  <link rel="alternate" hreflang="en" href="https://getfotocal.com/blog/">
  <link rel="alternate" hreflang="es" href="https://getfotocal.com/blog/">
  <link rel="alternate" hreflang="x-default" href="https://getfotocal.com/blog/">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Fotocal">
  <meta property="og:title" content="Fotocal Blog — nutrition, calories and habits">
  <meta property="og:description" content="{count} practical guides on nutrition, calorie counting, weight loss, macros and everyday habits.">
  <meta property="og:url" content="https://getfotocal.com/blog/">
  <meta property="og:image" content="https://getfotocal.com/assets/og-image.png">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="Fotocal Blog — nutrition, calories and habits">
  <meta name="twitter:description" content="{count} practical guides on nutrition, calorie counting, weight loss, macros and everyday habits.">
  <meta name="twitter:image" content="https://getfotocal.com/assets/og-image.png">
  <meta name="theme-color" media="(prefers-color-scheme: light)" content="#FFFFFF">
  <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#121212">
  <script type="application/ld+json">{ld}</script>
  <script type="application/ld+json">{ld_crumbs}</script>
  <link rel="icon" type="image/png" sizes="32x32" href="../assets/favicon-32.png?v=3">
  <link rel="icon" type="image/png" sizes="16x16" href="../assets/favicon-16.png?v=3">
  <link rel="icon" href="../assets/favicon.ico?v=3" sizes="32x32">
  <link rel="apple-touch-icon" sizes="180x180" href="../assets/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="192x192" href="../assets/icon-192.png">
  <link rel="manifest" href="../site.webmanifest">
  <link rel="stylesheet" href="../assets/css/fonts.css">
  <link rel="stylesheet" href="../assets/css/site.css">
  <link rel="stylesheet" href="../assets/css/home.css">
  <link rel="stylesheet" href="../assets/css/features.css">
  <link rel="stylesheet" href="../assets/css/blog.css">
</head>
<body class="page-fx page-blog">
<div id="site-nav"></div>

<main id="main">
  <section class="hero-x sec-dark fx-hero">
    <div class="container">
      <div class="fx-hero-inner">
        <div class="hero-glow" aria-hidden="true"></div>
        <span class="kicker reveal" data-i18n="blog.kicker">The Fotocal blog</span>
        <h1 class="hero-title reveal" data-i18n-html="blog.title">Notes on eating, <em class="accent">honestly</em>.</h1>
        <p class="hero-sub reveal" data-i18n="blog.lead">Practical, unglamorous writing on nutrition, weight and the habits that hold the whole thing together.</p>
      </div>
    </div>
  </section>

  <section class="section sec-light" id="all-posts">
    <div class="container">
      <!--# The featured card is the newest post. It is a filterable item like
           any other: same data-cat, counted by the chips, hidden when the
           active filter excludes it (assets/js/main.js, #blFeature). -->
      <a class="post-feature reveal" id="blFeature" data-cat="{f_cat}" href="{f_slug}/">
        <div class="post-feature-media"><img src="../assets/img/blog/{f_slug}.svg" width="1200" height="675" fetchpriority="high" decoding="async" alt=""></div>
        <div class="post-feature-body">
          <span class="post-feature-flag" data-i18n="blog.latest">Latest</span>
          <h2 data-lang-block="en">{f_title_en}</h2>
          <h2 data-lang-block="es">{f_title_es}</h2>
          <p data-lang-block="en">{f_lead_en}</p>
          <p data-lang-block="es">{f_lead_es}</p>
          <span class="post-card-meta"><span class="log-tag" data-i18n="blog.cat.{f_cat}">{f_cat_en}</span><span data-lang-block="en">{f_date_en} · {f_min_en} <span data-i18n="blog.min">min read</span></span><span data-lang-block="es">{f_date_es} · {f_min_es} <span data-i18n="blog.min">min de lectura</span></span></span>
        </div>
      </a>

      <div class="bl-filters reveal" role="group" aria-label="Filter posts by category">
        <button class="bl-chip" type="button" data-filter="all" aria-pressed="true"><span data-i18n="blog.all">All</span><span class="n">{count}</span></button>
{chips}
      </div>
      <p class="bl-count"><span id="blCount">{count}</span> <span data-i18n="blog.showing">articles</span></p>
      <div class="habit-grid sf-grid-3 post-grid" id="blGrid">
{cards}
      </div>
      <p class="bl-empty" id="blEmpty" hidden data-i18n="blog.none">No articles in this category yet.</p>
    </div>
  </section>

  <section class="final-band">
    <div class="container">
      <div class="final-band-inner reveal">
        <h2 data-i18n-html="blog.cta.title">Reading is good. <em class="accent-white">Doing is better</em>.</h2>
        <p data-i18n="blog.cta.sub">Put any of this into practice in about ten seconds a meal: photograph your plate and let Fotocal do the counting.</p>
        <a class="btn btn-white btn-lg" href="{play}" target="_blank" rel="noopener" data-i18n="cta.free">Get it free</a>
        <span class="final-note" data-i18n="cta.play">On Google Play · Android</span>
      </div>
    </div>
  </section>
</main>

<div id="site-footer"></div>
<script src="../assets/js/i18n.js"></script>
<script src="../assets/js/layout.js" data-page="blog"></script>
<script src="../assets/js/main.js"></script>
</body>
</html>
"""

CHIP = """        <button class="bl-chip" type="button" data-filter="{cat}" aria-pressed="false"><span data-i18n="blog.cat.{cat}">{cat_en}</span><span class="n">{n}</span></button>"""

def render_index():
    newest = by_date[-1]
    rest = list(reversed(by_date))[1:]
    counts = {}
    for p in posts:
        counts[p["category"]] = counts.get(p["category"], 0) + 1
    chips = "\n".join(CHIP.format(cat=c, cat_en=CAT_EN[c], n=n) for c, n in sorted(counts.items(), key=lambda x: (-x[1], x[0])))
    cards = "\n".join(card(q, "%s/" % q["slug"]).replace('class="habit-card sf-read post-card reveal"', 'class="habit-card sf-read post-card bl-card reveal" data-cat="%s"' % q["category"]) for q in rest)
    ld = json.dumps({"@context": "https://schema.org", "@type": "Blog", "name": "Fotocal Blog", "url": "https://getfotocal.com/blog/",
                     "publisher": {"@type": "Organization", "name": "Fotocal"},
                     "blogPost": [{"@type": "BlogPosting", "headline": strip_tags(q["en"]["title"]), "url": "https://getfotocal.com/blog/%s/" % q["slug"], "datePublished": q["date"]} for q in reversed(by_date)]}, ensure_ascii=False)
    ld_crumbs = json.dumps({"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "{{i18n:nav.home}}", "item": "https://getfotocal.com/"},
        {"@type": "ListItem", "position": 2, "name": "{{i18n:nav.blog}}", "item": "https://getfotocal.com/blog/"}]}, ensure_ascii=False)
    return INDEX.format(count=len(posts), ld=ld, ld_crumbs=ld_crumbs, play=PLAY, chips=chips, cards=cards,
                        f_slug=newest["slug"], f_cat=newest["category"], f_cat_en=CAT_EN[newest["category"]],
                        f_title_en=newest["en"]["title"], f_title_es=newest["es"]["title"], f_lead_en=newest["en"]["lead"], f_lead_es=newest["es"]["lead"],
                        f_date_en=fmt_date(newest["date"], "en"), f_date_es=fmt_date(newest["date"], "es"),
                        f_min_en=minutes(newest["en"]["body"]), f_min_es=minutes(newest["es"]["body"]))

# ── write ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    for i, p in enumerate(by_date):
        d = os.path.join(SRC, p["slug"])
        os.makedirs(d, exist_ok=True)
        open(os.path.join(d, "index.html"), "w", encoding="utf-8").write(render_post(p, i))
    open(os.path.join(SRC, "index.html"), "w", encoding="utf-8").write(render_index())
    inb = inbound()
    print("rendered %d posts + index; related: min inbound %d, orphans %d" % (len(posts), min(inb.values()), sum(1 for v in inb.values() if v == 0)))
